FROM chencd97/base:ubuntu_ojre17_latest

LABEL author="chencd97"
LABEL github="https://github.com/chencd97"
LABEL version="1.0.0"

ENV TZ=Asia/Shanghai
ENV LANG=C.UTF-8

RUN mkdir /home/docker

# 配置远程ssh的源文件
COPY ./sshd_config /etc/ssh/
COPY ./ssh_config /etc/ssh/
RUN chmod 644 /etc/ssh/sshd_config && chmod 644 /etc/ssh/ssh_config

COPY ./build_tasks.sh /home/docker
RUN chmod 755 /home/docker/build_tasks.sh && /home/docker/build_tasks.sh
RUN rm -rf /home/docker/build_tasks.sh

WORKDIR /home/docker

ENTRYPOINT ["sh", "/home/docker/_init.sh"]
